# Read deployment info generated by collect-deploy.py and output .git-ftp-include file

from __future__ import print_function
import argparse
import json
import sys

parser = argparse.ArgumentParser(description='Generate .git-ftp-include from deployment info')
parser.add_argument('deploy_files', nargs='+', metavar='DEPLOY_FILES', help='files produced by collect-deploy')
args = parser.parse_args()

for deploy_file in args.deploy_files:
    with (sys.stdin if deploy_file == "-" else open(deploy_file, "r")) as input_file:
        deploy_files = json.load(input_file)
        for to_deploy, deps in deploy_files.iteritems():
            for dep in deps:
                print('{0}:{1}'.format (to_deploy, dep))
